package LamportCorba;


/**
* LamportCorba/ListaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

public final class ListaHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Object value[] = null;

  public ListaHolder ()
  {
  }

  public ListaHolder (org.omg.CORBA.Object[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LamportCorba.ListaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LamportCorba.ListaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LamportCorba.ListaHelper.type ();
  }

}
