package LamportCorba;


/**
* LamportCorba/ListaSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

public final class ListaSHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListaSHolder ()
  {
  }

  public ListaSHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LamportCorba.ListaSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LamportCorba.ListaSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LamportCorba.ListaSHelper.type ();
  }

}
