package LamportCorba;


/**
* LamportCorba/ServidorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

public interface ServidorOperations 
{

  //somente metodos que serao invocados remotamente
  int entrarNoSD (org.omg.CORBA.Object servidor, String key);

  //adiciona nova maquina ao SD
  void updateSD (org.omg.CORBA.Object[] participantes, String[] chaves);

  //quando novas maquinas sao adicionadas ao SD
  void mensagemDoLider (int decisao);
  void mensagemDosMembros (int decisao);
  String requisicao_cliente (int requisicao);
} // interface ServidorOperations
