package LamportCorba;


/**
* LamportCorba/Servidor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

public interface Servidor extends ServidorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servidor
