package LamportCorba;

/**
* LamportCorba/ServidorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

public final class ServidorHolder implements org.omg.CORBA.portable.Streamable
{
  public LamportCorba.Servidor value = null;

  public ServidorHolder ()
  {
  }

  public ServidorHolder (LamportCorba.Servidor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LamportCorba.ServidorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LamportCorba.ServidorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LamportCorba.ServidorHelper.type ();
  }

}
