package LamportCorba;


/**
* LamportCorba/ServidorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Quarta-feira, 29 de Abril de 2015 20h05min51s BRT
*/

abstract public class ServidorHelper
{
  private static String  _id = "IDL:LamportCorba/Servidor:1.0";

  public static void insert (org.omg.CORBA.Any a, LamportCorba.Servidor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LamportCorba.Servidor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LamportCorba.ServidorHelper.id (), "Servidor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LamportCorba.Servidor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServidorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LamportCorba.Servidor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LamportCorba.Servidor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LamportCorba.Servidor)
      return (LamportCorba.Servidor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LamportCorba._ServidorStub stub = new LamportCorba._ServidorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LamportCorba.Servidor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LamportCorba.Servidor)
      return (LamportCorba.Servidor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LamportCorba._ServidorStub stub = new LamportCorba._ServidorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
